In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import pandas as pd

In [3]:
survey_data = pd.read_csv('data_cleaned.csv')
print(survey_data.shape)

survey_data.head()

(491, 12)

,gender,mother_tongue,mother_tongue_rating,no_of_fluent_languages,state,resided_in_the_same_city_from_birth,teaching_language_preference,notes_language_preference,questionpaper_language_preference,exam_in_regional_language,teaching_in_regional_language,knowledge_improvement
0,Female,Kannada,5.0,4,Karnataka,Yes,Hybrid language,Hybrid language,Regional language,Yes,Yes,Yes
1,Female,Kannada,5.0,3,Karnataka,Yes,English language,English language,English language,Yes,No,No
2,Male,Kannada,5.0,4,Karnataka,Yes,Hybrid language,Hybrid language,Hybrid language,Yes,Maybe,Yes
3,Female,Kannada,4.0,3,Karnataka,No,English language,English language,English language,Maybe,Maybe,Yes
4,Female,Kannada,5.0,5,Karnataka,Yes,Regional language,Hybrid language,Hybrid language,Yes,Yes,Yes

# Splitting the train and test set

In [4]:
X_train = pd.read_csv('X_train.csv')
X_test = pd.read_csv('X_test.csv')

In [5]:
X_train.head()

,mother_tongue_rating,no_of_fluent_languages,gender_Male,gender_Female,gender_Prefer not to say,mother_tongue_Kannada,mother_tongue_Telugu,mother_tongue_Tamil,mother_tongue_Hindi,mother_tongue_Konkani,...,notes_language_preference_Regional language,questionpaper_language_preference_English language,questionpaper_language_preference_Hybrid language,questionpaper_language_preference_Regional language,exam_in_regional_language_No,exam_in_regional_language_Yes,exam_in_regional_language_Maybe,teaching_in_regional_language_Yes,teaching_in_regional_language_No,teaching_in_regional_language_Maybe
0,5.0,3,1,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,0,0,1
1,5.0,2,0,1,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,0,1
2,4.0,2,1,0,0,0,0,1,0,0,...,1,0,0,1,0,1,0,1,0,0
3,5.0,3,1,0,0,1,0,0,0,0,...,0,0,1,0,0,1,0,0,0,1
4,5.0,3,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,1

In [6]:
X_test.head()

,mother_tongue_rating,no_of_fluent_languages,gender_Male,gender_Female,gender_Prefer not to say,mother_tongue_Kannada,mother_tongue_Telugu,mother_tongue_Tamil,mother_tongue_Hindi,mother_tongue_Konkani,...,notes_language_preference_Regional language,questionpaper_language_preference_English language,questionpaper_language_preference_Hybrid language,questionpaper_language_preference_Regional language,exam_in_regional_language_No,exam_in_regional_language_Yes,exam_in_regional_language_Maybe,teaching_in_regional_language_Yes,teaching_in_regional_language_No,teaching_in_regional_language_Maybe
0,5.0,3,0,1,0,0,1,0,0,0,...,0,0,1,0,0,1,0,1,0,0
1,5.0,4,0,1,0,0,0,1,0,0,...,0,0,1,0,0,1,0,1,0,0
2,5.0,3,0,1,0,1,0,0,0,0,...,0,0,1,0,0,1,0,1,0,0
3,5.0,2,1,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
4,4.0,3,1,0,0,0,1,0,0,0,...,0,1,0,0,1,0,0,1,0,0

In [7]:
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

In [8]:
y_train.head()

   knowledge_improvement
0                      1
1                      0
2                      0
3                      1
4                      2

In [9]:
y_test.head()

   knowledge_improvement
0                      2
1                      1
2                      1
3                      0
4                      1

# Feature Selection

In [10]:
from feature_engine.selection import SelectBySingleFeaturePerformance
from sklearn.ensemble import RandomForestClassifier

import matplotlib.pyplot as plt

rf = RandomForestClassifier(
    n_estimators=10, random_state=12, n_jobs=4)

sel = SelectBySingleFeaturePerformance(
    variables=None,
    estimator=rf,
    scoring="accuracy",
    cv=3)

sel.fit(X_train, y_train.values.ravel())

sel.feature_performance_

X_train = sel.transform(X_train)
X_test = sel.transform(X_test)

In [11]:
# Saving X_train and X_test
X_train.to_csv("X_train_model_features.csv", index = False)
X_test.to_csv("X_test_model_features.csv", index = False)

In [12]:
X_train.head()

,gender_Prefer not to say,mother_tongue_Kannada,mother_tongue_Telugu,mother_tongue_Hindi,state_Karnataka,state_Tamil nadu,teaching_language_preference_Regional language,notes_language_preference_Regional language,questionpaper_language_preference_Hybrid language,questionpaper_language_preference_Regional language,exam_in_regional_language_Maybe,teaching_in_regional_language_Yes,teaching_in_regional_language_No,teaching_in_regional_language_Maybe
0,0,1,0,0,1,0,0,0,1,0,0,0,0,1
1,0,1,0,0,1,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,1,1,0,1,0,1,0,0
3,0,1,0,0,1,0,0,0,1,0,0,0,0,1
4,0,0,1,0,0,0,0,0,1,0,1,0,0,1